suppressPackageStartupMessages(library(terra))
r<-rast(nrows=1,ncols=2,xmin=0,xmax=2000,ymin=0,ymax=1000,crs="EPSG:6933")
values(r)<-c(10,20)
a<-cellSize(r,unit="km");names(a)<-"area_km2"
zone<-as.polygons(ext(250,1750,0,1000),crs=crs(r))
w<-extract(a,zone,cells=TRUE,exact=TRUE)
actual<-sum(values(r,mat=FALSE)[w$cell]*w$area_km2*w$fraction)
expected<-.75*sum(values(r,mat=FALSE)*values(a,mat=FALSE))
stopifnot(abs(actual-expected)<1e-8*expected)
countries<-rbind(as.polygons(ext(0,1000,0,1000),crs=crs(r)),as.polygons(ext(1000,2000,0,1000),crs=crs(r)))
parts<-intersect(countries,zone)
cw<-extract(a,parts,cells=TRUE,exact=TRUE)
partitioned<-sum(values(r,mat=FALSE)[cw$cell]*cw$area_km2*cw$fraction)
stopifnot(abs(partitioned-actual)<1e-8*actual)
cat("2 exact-coverage and country-partition spatial test groups passed\n")
