suppressPackageStartupMessages(library(terra))
arg<-grep("^--file=",commandArgs(),value=TRUE)
root<-dirname(dirname(normalizePath(sub("^--file=","",arg),winslash="/")))
source(file.path(root,"R/core.R"))
args<-commandArgs(TRUE)
if(length(args)==1).libPaths(c(args[1],.libPaths()))
n<-0L
check<-function(label,x){if(!isTRUE(x))stop("FAIL: ",label);n<<-n+1L;cat("PASS",label,"\n")}
r<-rast(nrows=2,ncols=2,xmin=0,xmax=2000,ymin=0,ymax=2000,crs="EPSG:3395")
values(r)<-c(1,2,3,4)
e<-r;values(e)<-c(1,0,NA,1)
g<-ifel(e==1,r,NA)
check("unknown eligibility masks recovery",identical(as.numeric(values(g)),c(1,NA,NA,4)))
v<-as.polygons(ext(500,1500,0,2000),crs=crs(r))
z<-extract(r,v,fun=sum,exact=TRUE,na.rm=TRUE)
check("boundary cells receive fractional mass",abs(z[1,2]-5)<1e-8)
if(requireNamespace("exactextractr",quietly=TRUE)&&requireNamespace("sf",quietly=TRUE)){
  rr<-c(r,r*2);names(rr)<-c("a","b")
  zz<-exactextractr::exact_extract(rr,sf::st_as_sf(v),"sum",progress=FALSE,force_df=TRUE)
  check("fast exact engine has the expected layer order",identical(names(zz),c("sum.a","sum.b")))
  check("fast exact engine matches fractional mass",max(abs(as.numeric(zz[1,])-c(5,10)))<1e-8)
}else stop("Install sf and exactextractr to test the production zonal engine")
rr<-r;values(rr)<-c(1,NA,3,4)
s<-app(c(r,rr),"sum",na.rm=FALSE)
check("missing annual value propagates to period total",is.na(values(s)[2]))
stock<-r*10;A<-r*0+100;k<-r*0+.05;m<-r*0+2
recovery<-lapp(c(stock,A,k,m),function(b,a,kk,mm)cr_recovery(b,a,kk,mm,20)-b)
check("raster recovery stays nonnegative",global(recovery,"min")[1,1]>=0)
check("raster recovery respects capacity",global(recovery+stock-A,"max")[1,1]<=0)
high_latitude<-r;ext(high_latitude)<-c(0,2000,8000000,8002000)
check("Mercator cell ground area declines at high latitude",mean(values(cellSize(high_latitude,unit="ha")))<mean(values(cellSize(r,unit="ha")))/2)
cat(n,"spatial tests passed\n")
cat("External libraries:\n");print(gdal(lib="all"))
