arg<-grep("^--file=",commandArgs(),value=TRUE)
root<-dirname(dirname(normalizePath(sub("^--file=","",arg),winslash="/")))
source(file.path(root,"R","core.R"))
n<-0L
check<-function(label,x){if(!isTRUE(x))stop("FAIL: ",label);n<<-n+1L;cat("PASS",label,"\n")}
throws<-function(expr)inherits(tryCatch({force(expr);NULL},error=function(e)e),"error")
check("2030 uses frame 31 for a 2000 start",frame_for_year(2030,2000:2050)==31)
check("2050 uses frame 51",frame_for_year(2050,2000:2050)==51)
check("duplicate year fails",throws(frame_for_year(2030,c(2030,2030))))
check("missing year fails",throws(frame_for_year(2051,2000:2050)))
check("nonconsecutive index fails",throws(frame_for_year(2030,c(2028,2030))))
check("zero horizon preserves stock",abs(cr_recovery(20,100,.05,2,0)-20)<1e-12)
check("stock above capacity never decreases",cr_recovery(150,100,.05,2,20)==150)
check("zero stock has positive conditional regeneration",cr_recovery(0,100,.05,2,20)>0)
check("invalid parameters are missing",all(is.na(cr_recovery(c(10,-1),c(0,100),.05,2,20))))
check("missing stock is missing",is.na(cr_recovery(NA,100,.05,2,20)))
B<-cr_recovery(20,100,.05,2,10)
check("semigroup gives the same 20-year advance",abs(cr_recovery(B,100,.05,2,10)-cr_recovery(20,100,.05,2,20))<1e-10)
check("slower growth lowers conditional recovery",cr_recovery(20,100,.05,2,20,.75)<cr_recovery(20,100,.05,2,20))
check("gain cannot exceed remaining capacity",cr_recovery(20,100,.05,2,10000)<=100)
check("CO2 to biomass conversion follows units",abs(co2_to_dry_biomass(44*.47)-12)<1e-12)
check("negative observed estimates are missing not zero",is.na(co2_to_dry_biomass(-1)))
check("zero harvest gives missing ratio",is.na(pressure_share(1,0)))
check("ratio above one remains visible",pressure_share(5,2)==2.5)
tab<-data.frame("Key*"=1:4,LULC=c("X_Mixed Forests","X_Grasslands","X_Croplands","X_Woody Savannas"),check.names=FALSE)
check("grasslands and cropland excluded",identical(eligibility_table(tab)$screening_eligible,c(1L,0L,0L,1L)))
check("woody savanna can be disabled",eligibility_table(tab,FALSE)$screening_eligible[4]==0)
all_classes<-data.frame("Key*"=1:11,LULC=paste0("Test biome_",c("Evergreen Broadleaf Forests","Deciduous Broadleaf Forests","Mixed Forests","Woody Savannas","Savannas","Grasslands","Open Shrublands","Closed Shrublands","Croplands","Permanent Wetlands","Urban and Built-up Lands")),check.names=FALSE)
check("native woody default includes forests and woody savanna only",identical(eligibility_table(all_classes)$screening_eligible,c(rep(1L,4),rep(0L,7))))
check("forest-only sensitivity excludes woody savanna",identical(eligibility_table(all_classes,FALSE)$screening_eligible,c(rep(1L,3),rep(0L,8))))
check("missing woody-scope choice fails",throws(eligibility_table(tab,NA)))
check("nonboolean woody-scope choice fails",throws(eligibility_table(tab,"true")))
caption<-screening_caption_lines(TRUE,2)
check("release caption is v1",grepl("Version 1.0.0",caption[1],fixed=TRUE))
check("caption retains zero-harvest and stable-land-use assumptions",grepl("Zero-harvest",caption[1],fixed=TRUE)&&grepl("stable land use",caption[1],fixed=TRUE))
check("caption identifies historical scope and current-land-use check",grepl("Historical 2001 forest/woody-savanna",caption[2],fixed=TRUE)&&grepl("Verify current land use",caption[2],fixed=TRUE))
check("caption guards natural open ecosystems",grepl("not afforestation targets",caption[3],fixed=TRUE))
check("caption disclaims intervention and carbon-credit claims",grepl("not an intervention impact",caption[4],fixed=TRUE)&&grepl("carbon-credit estimate",caption[4],fixed=TRUE))
check("forest-only caption follows explicit sensitivity setting",grepl("forest-only",screening_caption_lines(FALSE,2)[2],fixed=TRUE))
check("caption rejects invalid realization count",throws(screening_caption_lines(TRUE,0)))
check("excluded land cannot be priority",priority_class(50,5,.5,0)==0)
check("high recovery and pressure class",priority_class(50,5,.5,1)==4)
check("ratio above one gets review class",priority_class(50,5,1.5,1)==5)
check("unknown eligibility stays unknown",is.na(priority_class(50,5,.5,NA)))
check("missing recovery stays unknown",is.na(priority_class(NA,5,.5,1)))
check("depletion without a valid harvest denominator requires review",priority_class(50,5,NA,1)==5)
if(requireNamespace("terra",quietly=TRUE)){
 r<-terra::rast(nrows=2,ncols=2,xmin=0,xmax=2,ymin=0,ymax=2)
 s<-terra::rast(nrows=2,ncols=2,xmin=1,xmax=3,ymin=0,ymax=2)
 check("shifted raster grid fails",throws(check_same_grid(list(r,s))))
}
typ<-investment_typology(c(10,100,10,100),c(.1,.1,.8,.8))
check("strategy typology preserves all four combinations",identical(typ$class,c("Lower priority","Major supply-shed","Fragile/local","Critical")))
check("zero burden is never critical",investment_typology(c(0,0),c(0,0))$class[1]=="Lower priority")
check("out-of-range fNRB is not silently capped",is.na(investment_typology(c(1,2),c(.2,1.2))$class[2]))
check("missing data cannot change the tercile cut-point",identical(investment_typology(c(10,100,10,100,NA),c(.1,.1,.8,.8,.5))$nrb_cutpoint,typ$nrb_cutpoint))
check("typology rejects unequal vector lengths",throws(investment_typology(c(1,2),.2)))
cat(n,"tests passed\n")
